# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', simditor.fields.RichTextField()),
            ],
        ),
    ]
